name: 4Tzones-utils
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - Cython
    - matplotlib
    - jupyter
    - ffmpeg
    - imageio==2.1.2
    - libprotobuf
    - icu==56.1
    - pip:
        - imgaug==0.2.7
        - attrdict==2.0.0
        - eventlet==0.19.0
        - python-socketio==1.6.1
        - numpy==1.13.1
        - scipy==0.19.1
        - keras==2.1.5
        - h5py==2.6.0
        - opencv-python==4.0.0.21
        - PyYAML==3.13
        - moviepy==0.2.3.5
        - https://github.com/mind/wheels/releases/download/tf1.3.1-gpu/tensorflow-1.3.1-cp36-cp36m-linux_x86_64.whl
